### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by ebachard** [43437/opengYUV#1]
Hello,

Your idea is very interesting, but I can't find any information about the license you are using for your code.

Thanks in advance for your answer :-)

**Comment by 43437** [comment]
sorry, i don't think about licenses, in this demo i use opengl, if opengl or something i use does have license, then my demo must obey, if that does not have license, my demo's license will be WTFPL license.

**Comment by ebachard** [comment]
Hello,

My question was about reuse your code respecting the original licensing:
- the YUV to OpenGL part through pixel shaders is extremely interesting for me
- I'll probably reuse a part of it first under LGPL, and some times after under MIT or similar license

Thanks a lot for your clarification.

Last but not least, I'll reverse you some fixes I did on Linux (will create a PR asap), the time to find an example
